package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.City
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping

class CityRepository : AbstractRepository<Int, City>(
    EntityMapping(
        "city",
        { City() },
        listOf(
            EntityMapping.Field(
                true, isAutogenerated = true, columnName = "id", plainType = Int::class.java,
                getter = { id }, setter = { id = it!! }
            ),
            EntityMapping.Field(
                true, isAutogenerated = false, columnName = "name", plainType = String::class.java,
                getter = { name }, setter = { name = it!! }
            ),
        )
    )
)