package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.City
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping

class CityRepository : AbstractRepository<Int, City>(
    EntityMapping(
        "city",
        { City() },
        listOf(
            EntityMapping.Field(
                columnName = "id", plainType = Int::class.java, true, isAutogenerated = true,
                getter = { id }
            ) { id = it!! },
            EntityMapping.Field(
                columnName = "name", plainType = String::class.java, true, isAutogenerated = false,
                getter = { name }
            ) { name = it!! },
        )
    )
)