package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.Country
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping

class CountryRepository : AbstractRepository<String, Country>(
    EntityMapping(
        "country",
        { Country() },
        listOf(
            EntityMapping.Field(
                columnName = "key",
                plainType = String::class.java,
                true,
                isAutogenerated = true,
                getter = { key }
            ) { key = it!! },
            EntityMapping.Field(
                columnName = "name",
                plainType = String::class.java,
                isId = true,
                isAutogenerated = false,
                getter = { name }
            ) { name = it!! },
        )
    )
)