package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.Country
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping

class CountryRepository : AbstractRepository<String, Country>(
    EntityMapping(
        "country",
        { Country() },
        listOf(
            EntityMapping.Field(
                true,
                isAutogenerated = true,
                columnName = "key",
                plainType = String::class.java,
                getter = { key },
                setter = { key = it!! }
            ),
            EntityMapping.Field(
                isId = true,
                isAutogenerated = false,
                columnName = "name",
                plainType = String::class.java,
                getter = { name },
                setter = { name = it!! }
            ),
        )
    )
)