package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.Deposit
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping
import java.time.Period

class DepositProgramRepository : AbstractRepository<Int, Deposit.Program>(
    EntityMapping(
        "deposit_program",
        { Deposit.Program() },
        listOf(
            EntityMapping.Field(
                "id", Int::class.java,
                isId = true, isAutogenerated = true,
                getter = { id }, setter = { id = it!! }
            ),
            EntityMapping.Field(
                "name", String::class.java,
                isId = true, isAutogenerated = false,
                getter = { name }, setter = { name = it!! }
            ),
            EntityMapping.Field(
                "revocable", Boolean::class.java,
                isId = false, isAutogenerated = false,
                getter = { revocable }, setter = { revocable = it!! }
            ),
            EntityMapping.Field(
                "period", String::class.java,
                isId = false, isAutogenerated = false,
                getter = { period.toString().drop(1) },
                setter = { period = Period.parse("P" + it!!) }
            ),
            EntityMapping.Field(
                "first_payment", Int::class.java,
                isId = false, isAutogenerated = false,
                getter = { firstPayment }, setter = { firstPayment = it!! }
            ),
            EntityMapping.Field(
                "percent_strategy", String::class.java,
                isId = false, isAutogenerated = false,
                getter = { percentStrategy.toString() }, setter = { percentStrategy = Deposit.Strategy.parse(it!!) }
            ),
            EntityMapping.Field(
                columnName = "replenishment", plainType = String::class.java,
                isId = false, isAutogenerated = false,
                getter = { replenishment }
            ) { replenishment = it!! },
            EntityMapping.Field(
                columnName = "expenditure_operations", plainType = String::class.java,
                isId = false, isAutogenerated = false,
                getter = { expenditureOperations }
            ) { expenditureOperations = it!! },
            EntityMapping.Field(
                columnName = "auto_prolongation", plainType = Boolean::class.java,
                isId = false, isAutogenerated = false,
                getter = { autoProlongation }
            ) { autoProlongation = it!! },
        )
    )
)