package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.Disability
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping

class DisabilityRepository : AbstractRepository<Int, Disability>(
    EntityMapping(
        "disability",
        { Disability() },
        listOf(
            EntityMapping.Field(
                columnName = "id",
                plainType = Int::class.java,
                true,
                isAutogenerated = true,
                getter = { id }
            ) { id = it!! },
            EntityMapping.Field(
                columnName = "name",
                plainType = String::class.java,
                true,
                isAutogenerated = false,
                getter = { name }
            ) { name = it!! },
        )
    )
)