package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.Disability
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping

class DisabilityRepository : AbstractRepository<Int, Disability>(
    EntityMapping(
        "disability",
        { Disability() },
        listOf(
            EntityMapping.Field(
                true,
                isAutogenerated = true,
                columnName = "id",
                plainType = Int::class.java,
                getter = { id },
                setter = { id = it!! }
            ),
            EntityMapping.Field(
                true,
                isAutogenerated = false,
                columnName = "name",
                plainType = String::class.java,
                getter = { name },
                setter = { name = it!! }
            ),
        )
    )
)