package by.varyvoda.bankapp.domain.repository.impl

import by.varyvoda.bankapp.domain.model.MaritalStatus
import by.varyvoda.bankapp.domain.repository.AbstractRepository
import by.varyvoda.bankapp.domain.repository.mapping.EntityMapping

class MaritalStatusRepository : AbstractRepository<Int, MaritalStatus>(
    EntityMapping(
        "marital_status",
        { MaritalStatus() },
        listOf(
            EntityMapping.Field(
                columnName = "id",
                plainType = Int::class.java,
                true,
                isAutogenerated = true,
                getter = { id }
            ) { id = it!! },
            EntityMapping.Field(
                columnName = "name",
                plainType = String::class.java,
                true,
                isAutogenerated = false,
                getter = { name }
            ) { name = it!! },
        )
    )
)