package by.varyvoda.bankapp.domain.repository.mapping

class EntityMapping<E>(
    val tableName: String,
    val creator: () -> E,
    val fields: List<Field<E, out Any>>
) {

    val idField = fields.find { it.isId }!!

    val nonGeneratedFields = fields.filter { !it.isAutogenerated }

    fun getField(columnName: String): Field<E, out Any> {
        return fields.find { it.columnName == columnName }!!
    }

    class Field<E, FT>(
        val columnName: String,
        val plainType: Class<FT>,
        val isId: Boolean,
        val isAutogenerated: Boolean,
        val getter: E.() -> FT?,
        val setter: E.(FT?) -> Unit,
    )
}